### PR TITLE
add join nested

### PR DESCRIPTION
**Pull request by wzrdtales**
This adds functionality for easily passing in bulk inserts.

Signed-off-by: Tobias Gurtzick <magic@wizardtales.com>

### CODE REVIEW

**Comment by wzrdtales** [comment]
ping @blakeembrey

**Comment by wzrdtales** [comment]
ping @blakeembrey

**Comment by blakeembrey** [comment]
Hi, I was on vacation. Taking a look now, isn't this effectively just this?

```ts
export function joinNested(values: Array<RawValue[]>) {
  return join(values.map(x => join(x));
}
```

Any reason for the additional complexity? We can even add the extra separator argument and just pass that through to the `join` function.

**Comment by wzrdtales** [comment]
i just used your own methods and the rest is error handling

**Comment by wzrdtales** [comment]
using your suggestion works, but would return wrong error messages, the main reason to do it this way is to have it distinct.

**Comment by wzrdtales** [comment]
More explanation, my implementation reports a detailed error:

```
Expected joinNested([][5]) instead param at index 7 had a length of 4
```

So the user directly knows here what is wrong, if just calling join here, it would return a completely misleading error.

**Comment by wzrdtales** [comment]
bug bug @blakeembrey

**Comment by wzrdtales** [comment]
again some follow up, we're using our hard fork already so take your time deciding, just making sure it doesn't go under the radar completely.

**Comment by wzrdtales** [comment]
buggedy bug @blakeembrey

**Comment by blakeembrey** [comment]
Sorry for the delay, I've been effectively AWOL. I might rename it and will add to the README before the next release.

**Comment by wzrdtales** [comment]
No worries, we maintain our module, so we were not waiting, :) 

Hope you're doing well.

**Pull request merged**
